/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RestaurantView;
import RestaurantModel.*;
import RestaurantController.*;
import static RestaurantView.table_frame.order;
import static RestaurantView.table_frame.orderListData;
import static RestaurantView.table_frame.order_controller;
import static RestaurantView.table_frame.table;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JFrame;


/**
 *
 * @author zeliha
 */
public class calculate_check_frame extends javax.swing.JFrame {

    public OrderController order_controller = new OrderController();
    public Order order;
    public JButton button;
    public Table table;
    public JFrame frame;
    /**
     * Creates new form frame5
     */
    
    public calculate_check_frame(){
        
    }
    public calculate_check_frame(JFrame frame, Order order,Table table, JButton button) {
        this.frame=frame;
        this.table=table;
        this.order =order;
        this.button=button;
        initComponents();
        list_order();
        caluclate_total_tip();
        
    }
    public void list_order(){
        ArrayList<String> arraylist = order_controller.listOrder(order);
        for(String n : arraylist){
            orders_list.add(n);
            

        }
        ArrayList<Integer> arraylist2 = order_controller.listOrderQuantity(order);
        for(Integer n : arraylist2){
            orders_price_list.add(String.valueOf(n));
            
        } 
    }
    
    public void caluclate_total_tip(){
        totall.setText(""+OrderController.calculate(order));
        tip.setText(""+OrderController.calculate(order)/10);
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        calculate_check_label = new javax.swing.JLabel();
        pay_in_one_button = new javax.swing.JButton();
        pay_seperately_button = new javax.swing.JButton();
        orders_labels = new javax.swing.JLabel();
        tip_label = new javax.swing.JLabel();
        total_label = new javax.swing.JLabel();
        return_button = new javax.swing.JButton();
        orders_labels1 = new javax.swing.JLabel();
        close_table_button = new javax.swing.JButton();
        scrollPane1 = new java.awt.ScrollPane();
        orders_list = new java.awt.List();
        scrollPane2 = new java.awt.ScrollPane();
        orders_price_list = new java.awt.List();
        tip = new javax.swing.JLabel();
        totall = new javax.swing.JLabel();
        update_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        calculate_check_label.setForeground(new java.awt.Color(102, 102, 102));
        calculate_check_label.setText("Calculate Check");

        pay_in_one_button.setText("Pay in one");
        pay_in_one_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_in_one_buttonActionPerformed(evt);
            }
        });

        pay_seperately_button.setText("Pay seperately");
        pay_seperately_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_seperately_buttonActionPerformed(evt);
            }
        });

        orders_labels.setText("Count:");

        tip_label.setText("Tip:");

        total_label.setText("Total:");

        return_button.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        return_button.setText("Return");
        return_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return_buttonActionPerformed(evt);
            }
        });

        orders_labels1.setText("Orders:");

        close_table_button.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        close_table_button.setText("Close Table");
        close_table_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_table_buttonActionPerformed(evt);
            }
        });

        scrollPane1.add(orders_list);

        scrollPane2.add(orders_price_list);

        tip.setText("0.0");

        totall.setText("0.0");

        update_button.setText("Update");
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pay_seperately_button)
                            .addComponent(pay_in_one_button, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(close_table_button, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tip_label, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(total_label, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totall)
                                    .addComponent(tip)))))
                    .addComponent(calculate_check_label))
                .addGap(160, 160, 160)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(orders_labels1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(orders_labels))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(update_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(return_button)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {close_table_button, pay_in_one_button, pay_seperately_button});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(calculate_check_label)
                            .addComponent(return_button)
                            .addComponent(update_button))
                        .addGap(48, 48, 48)
                        .addComponent(pay_in_one_button, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pay_seperately_button, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tip_label)
                            .addComponent(tip))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(total_label)
                            .addComponent(totall))
                        .addGap(18, 18, 18)
                        .addComponent(close_table_button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(orders_labels1)
                            .addComponent(orders_labels))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(scrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(scrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE))))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {close_table_button, pay_in_one_button, pay_seperately_button});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pay_in_one_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_in_one_buttonActionPerformed
        pay_one_frame frame =new pay_one_frame();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_pay_in_one_buttonActionPerformed

    private void return_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_return_buttonActionPerformed
        dispose();
    }//GEN-LAST:event_return_buttonActionPerformed

    private void pay_seperately_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_seperately_buttonActionPerformed
        pay_seperately_frame frame =new pay_seperately_frame();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_pay_seperately_buttonActionPerformed

    private void close_table_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_table_buttonActionPerformed
        table.setAvailable(false);   
        main_page.changeColor(button,table);
        order.closeOrder();
        frame.dispose();
        dispose();
    }//GEN-LAST:event_close_table_buttonActionPerformed

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed
        orders_list.removeAll();
        orders_price_list.removeAll();
        list_order();
        caluclate_total_tip();
        invalidate();
        validate();
        repaint(); // TODO add your handling code here:
    }//GEN-LAST:event_update_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculate_check_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculate_check_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculate_check_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculate_check_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculate_check_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel calculate_check_label;
    private javax.swing.JButton close_table_button;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel orders_labels;
    private javax.swing.JLabel orders_labels1;
    private java.awt.List orders_list;
    private java.awt.List orders_price_list;
    private javax.swing.JButton pay_in_one_button;
    private javax.swing.JButton pay_seperately_button;
    private javax.swing.JButton return_button;
    private java.awt.ScrollPane scrollPane1;
    private java.awt.ScrollPane scrollPane2;
    private javax.swing.JLabel tip;
    private javax.swing.JLabel tip_label;
    private javax.swing.JLabel total_label;
    private javax.swing.JLabel totall;
    private javax.swing.JButton update_button;
    // End of variables declaration//GEN-END:variables
}
