/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RestaurantView;

import java.awt.*;
import javax.swing.*;
import RestaurantController.*;
import RestaurantModel.*;

/*
 *
 * @author yaseminorhun
 */

public class enter_ID extends javax.swing.JFrame {
    /**
     * Creates new form login_page
     */
    public JButton button;
    public Table table;
    public enter_ID() {
        initComponents();
    }
    
    public enter_ID(Table table,JButton button) {
        this.table=table;
        this.button=button;
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        enter_ID_panel = new javax.swing.JPanel();
        enter_button = new javax.swing.JToggleButton();
        cancel_button = new javax.swing.JToggleButton();
        ID_text_field = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        enter_ID_panel.setBackground(new java.awt.Color(255, 255, 255));

        enter_button.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        enter_button.setText("enter");
        enter_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enter_buttonActionPerformed(evt);
            }
        });

        cancel_button.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        cancel_button.setText("cancel");
        cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_buttonActionPerformed(evt);
            }
        });

        ID_text_field.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        ID_text_field.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ID_text_field.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setText("Enter your  ID:");

        javax.swing.GroupLayout enter_ID_panelLayout = new javax.swing.GroupLayout(enter_ID_panel);
        enter_ID_panel.setLayout(enter_ID_panelLayout);
        enter_ID_panelLayout.setHorizontalGroup(
            enter_ID_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enter_ID_panelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(enter_ID_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(enter_ID_panelLayout.createSequentialGroup()
                        .addComponent(cancel_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(enter_button))
                    .addGroup(enter_ID_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ID_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        enter_ID_panelLayout.setVerticalGroup(
            enter_ID_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enter_ID_panelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(enter_ID_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(enter_ID_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel_button)
                    .addComponent(enter_button))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        enter_ID_panelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cancel_button, enter_button});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enter_ID_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enter_ID_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void enter_buttonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        if (ID_text_field.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,  "The field cannot be left blank. You must enter a valid ID!" ,"Permission Error!", JOptionPane.INFORMATION_MESSAGE);
            }     
        else{
            
            table.setAvailable(true);
            main_page.changeColor(button, table);
            table_frame frame =new table_frame(ID_text_field.getText(),table,button);
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
            
            this.dispose();
        }             
    }                                            

    private void cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {                                              
         dispose();
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(enter_ID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(enter_ID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(enter_ID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(enter_ID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new enter_ID().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JTextField ID_text_field;
    private javax.swing.JToggleButton cancel_button;
    private javax.swing.JPanel enter_ID_panel;
    private javax.swing.JToggleButton enter_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration                   
}
