/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package RestaurantView;

import java.awt.*;
import java.util.*;
import javax.swing.*;

import RestaurantController.*;
import RestaurantModel.*;



public class table_frame extends javax.swing.JFrame {
    public static Table table;
    public static String user_ID;
    public static OrderController order_controller = new OrderController();
    public static Order order;
    public static JButton button;

    /** Creates new form frame4 */
     public table_frame(String user_ID, Table table,JButton button) {
        initComponents();
        this.table =table;
        this.user_ID=user_ID;     
        this.button=button;
        orderListData(table);
        setUserID();  
        setTableID();
    }
    
    public void setTableID(){   
        table_ID_label.setText("Table ID : "+ table.getTableId());       
    }
    
    public void setUserID(){
        user_ID_label.setText("Waiter/Waiteress ID : " + user_ID);  
    }
    
    public static void orderListData(Table table){       
        order = order_controller.createOrder(table);        
        ArrayList<String> arraylist = order_controller.listOrder(order);
        for(String n : arraylist){
            orders_list.add(n);
        } 
        ArrayList<Integer> arraylist2 = order_controller.listOrderQuantity(order);
        for(Integer n : arraylist2){
            count_list.add(String.valueOf(n));
            
        } 
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        panel = new javax.swing.JPanel();
        table_ID_label = new javax.swing.JLabel();
        main_dishes_button = new javax.swing.JButton();
        dessert_button = new javax.swing.JButton();
        beverages_button = new javax.swing.JButton();
        orders_label = new javax.swing.JLabel();
        calculate_check_button = new javax.swing.JButton();
        user_ID_label = new javax.swing.JLabel();
        return_button = new javax.swing.JButton();
        orders_pane = new java.awt.ScrollPane();
        orders_list = new java.awt.List();
        jLabel1 = new javax.swing.JLabel();
        update_button = new javax.swing.JButton();
        count_pane = new java.awt.ScrollPane();
        count_list = new java.awt.List();
        jLabel2 = new javax.swing.JLabel();

        panel.setBackground(new java.awt.Color(255, 255, 255));

        table_ID_label.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        table_ID_label.setText("Table ID:");

        main_dishes_button.setBackground(new java.awt.Color(204, 204, 204));
        main_dishes_button.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        main_dishes_button.setText("Main Dishes");
        main_dishes_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                main_dishes_buttonActionPerformed(evt);
            }
        });

        dessert_button.setBackground(new java.awt.Color(204, 204, 204));
        dessert_button.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        dessert_button.setText("Desserts");
        dessert_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dessert_buttonActionPerformed(evt);
            }
        });

        beverages_button.setBackground(new java.awt.Color(204, 204, 204));
        beverages_button.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        beverages_button.setText("Beverages");
        beverages_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beverages_buttonActionPerformed(evt);
            }
        });

        orders_label.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 10)); // NOI18N
        orders_label.setText("Orders");

        calculate_check_button.setBackground(new java.awt.Color(255, 255, 255));
        calculate_check_button.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        calculate_check_button.setText("Calculate Check");
        calculate_check_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculate_check_buttonActionPerformed(evt);
            }
        });

        user_ID_label.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        user_ID_label.setText("Waiter/Waitress ID:");

        return_button.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        return_button.setText("Return");
        return_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return_buttonActionPerformed(evt);
            }
        });

        orders_pane.add(orders_list);

        update_button.setText("Update");
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });

        count_pane.add(count_list);

        jLabel2.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 10)); // NOI18N
        jLabel2.setText("Count");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calculate_check_button, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(beverages_button, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dessert_button, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(main_dishes_button, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(user_ID_label, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(table_ID_label, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(orders_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orders_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(update_button, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(return_button))
                    .addComponent(jLabel2)
                    .addComponent(count_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );

        panelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {count_pane, orders_pane});

        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(table_ID_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(user_ID_label, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(return_button)
                            .addComponent(update_button))))
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(orders_label)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(count_pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(orders_pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(main_dishes_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dessert_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(beverages_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147)
                        .addComponent(calculate_check_button, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>                        

    private void return_buttonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        dispose();
    }                                             

    private void calculate_check_buttonActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        calculate_check_frame frame =new calculate_check_frame(this,order,table,button);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
       
    }                                                      

    private void beverages_buttonActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        edit_order_frame frame =new edit_order_frame(table,"Beverages",order);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);     // TODO add your handling code here:
    }                                                

    private void dessert_buttonActionPerformed(java.awt.event.ActionEvent evt) {                                               

        edit_order_frame frame =new edit_order_frame(table,"Desserts",order);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);    // TODO add your handling code here:
    }                                              

    private void main_dishes_buttonActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        edit_order_frame frame =new edit_order_frame(table,"Main Dishes",order);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);        // TODO add your handling code here:
    }                                                  

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        orders_list.removeAll();
        count_list.removeAll();
        orderListData(table);
        invalidate();
        validate();
        repaint();
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(table_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(table_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(table_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(table_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new table_frame(user_ID,table,button).setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton beverages_button;
    private javax.swing.JButton calculate_check_button;
    private static java.awt.List count_list;
    private java.awt.ScrollPane count_pane;
    private javax.swing.JButton dessert_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton main_dishes_button;
    private javax.swing.JLabel orders_label;
    private static java.awt.List orders_list;
    private static java.awt.ScrollPane orders_pane;
    private static javax.swing.JPanel panel;
    private javax.swing.JButton return_button;
    private javax.swing.JLabel table_ID_label;
    private javax.swing.JButton update_button;
    private javax.swing.JLabel user_ID_label;
    // End of variables declaration                   

}
